### ISSUE TITLE
Missing relevant data files?

### ISSUE THREAD

**Issue by HYD-PG** [ZhengdaoLI0602/GNSS_INS_Integrations_Comparisons#1]

**Comment by ZhengdaoLI0602** [comment]
Dear Yudong,

Many thanks for your message. You can actually get access to the data via the link in README.md when you enter the folder "EnvFolder", as shown in the attached figure. Hope this would help solve your confusion and have a nice day!


<img width="811" alt="release" src="https://github.com/ZhengdaoLI0602/GNSS_INS_Integrations_Comparisons/assets/80500317/b45af4cd-5c08-49d3-8c00-136d008daaed">
