### ISSUE TITLE
运行AKF时报错

### ISSUE THREAD

**Issue by kysdmby** [ZhengdaoLI0602/GNSS_INS_Integrations_Comparisons#2]
感谢您的分享，我在运行您的程序时，运行完kf后 运行AKF时发生报错，请问是什么原因。报错内容如下：

错误使用 AdaptiveR
输入参数太多。

出错 LCKF_INS_GNSS_debug (第 203 行)
                adaptiveR = AdaptiveR(GNSS_data{GNSS_epoch, 1}, ml_prediction, fixed_uct, receiver);

出错 Main_GNSS_INS_Integration (第 102 行)
    [SVs, LCKF_result, GNSS_llh, IMU_Data, Ucts] = LCKF_INS_GNSS_debug(GNSS_Data,IMU_Data,LC_KF_config, Fixed_KF_Uct, ml_prediction, whether_adaptive, receiver);

**Comment by ZhengdaoLI0602** [comment]
多谢指正。
应当把”LCKF_INS_GNSS_debug.m“第203行 “AdaptiveR” 函数当中的 "fixed_uct" 参数删去。更新过的GitHub仓库已经更新。

**Comment by kysdmby** [comment]
好的。感谢您的及时回复！
